### ISSUE TITLE
Region name should use the configured default AWS region (not us-east-1)

### ISSUE THREAD

**Issue by hjacobs** [obsrvbl/flowlogs-reader#14]
The AWS region name is currently hardcoded to us-east-1, but it should use Boto's default behavior (e.g. using the default region configured in ~/.aws/config):

https://github.com/obsrvbl/flowlogs-reader/blob/master/flowlogs_reader/flowlogs_reader.py#L128

**Comment by bbayles** [comment]
Yes, you're right. I'll issue a fix shortly.
