### ISSUE TITLE
CloudWatch vs S3 performance for real-time monitoring

### ISSUE THREAD

**Issue by BrijMohanD** [obsrvbl/flowlogs-reader#50]
This is not an issue. Just want to know your opinion, which is the best - CloudWatch logs vs S3 logs in terms of performance using this library for same infrastructure?

**Comment by bbayles** [comment]
I'm speaking here as an individual and not on behalf of my employer, municipality, or family unit. This is not legal, medical, or financial advice: S3 is way better.
